name: CI

on:
  [pull_request]


jobs:
 job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Test Build
        run: |
          if [ -e yarn.lock ]; then
          yarn install  --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
